"""empty message

Revision ID: 5f026d9a6649
Revises: e4d25b67533d
Create Date: 2016-02-03 18:08:44.640729

"""

# revision identifiers, used by Alembic.
revision = '5f026d9a6649'
down_revision = 'e4d25b67533d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_job', sa.Column('pid', sa.SmallInteger(), nullable=True))
    op.add_column('export_job', sa.Column('status', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_job', 'status')
    op.drop_column('export_job', 'pid')
    ### end Alembic commands ###
