"""empty message

Revision ID: 70577ca83399
Revises: c252e4851521
Create Date: 2016-07-21 04:36:29.792149

"""

# revision identifiers, used by Alembic.
revision = '70577ca83399'
down_revision = 'c252e4851521'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_job', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text(u'0'), nullable=False))
    op.add_column('export_job', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_job', 'updated_at')
    op.drop_column('export_job', 'created_at')
    ### end Alembic commands ###
